name: qr_perpustakaan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^2.17.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.8.0
  flutter_lints: ^4.0.0
  mobile_scanner: ^6.0.2
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  permission_handler: ^10.0.0
  
flutter:
  uses-material-design: true
